//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/common/common-attribs.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is the common attributes module for MathML.
//	Author: Stéphane Dalmas, INRIA.
import (
	xlink "github.com/metaleap/go-xsd/pkg/www.w3.org/Math/XMLSchema/mathml2/common/xlink-href.xsd_gopkg"
	xsdt "github.com/metaleap/go-xsd/types"
)

type XsdGoPkgHasAttr_Class_XsdtNmtokens_ struct {
	Class xsdt.Nmtokens `xml:"http://www.w3.org/1998/Math/MathML class,attr"`
}

type XsdGoPkgHasAttr_Style_XsdtString_ struct {
	Style xsdt.String `xml:"http://www.w3.org/1998/Math/MathML style,attr"`
}

type XsdGoPkgHasAttr_Xref_XsdtIdref_ struct {
	Xref xsdt.Idref `xml:"http://www.w3.org/1998/Math/MathML xref,attr"`
}

type XsdGoPkgHasAttr_Id_XsdtId_ struct {
	Id xsdt.Id `xml:"http://www.w3.org/1998/Math/MathML id,attr"`
}

type XsdGoPkgHasAtts_CommonAttrib struct {
	XsdGoPkgHasAttr_Class_XsdtNmtokens_
	XsdGoPkgHasAttr_Style_XsdtString_
	XsdGoPkgHasAttr_Xref_XsdtIdref_
	XsdGoPkgHasAttr_Id_XsdtId_
	xlink.XsdGoPkgHasAttr_Href
}
