//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/content/vector-calculus.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is an XML Schema module for the vector calculs operators of content
//	MathML.
//	Author: Stéphane Dalmas, INRIA.
import (
)

type XsdGoPkgHasAtts_DivergenceAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_GradAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_CurlAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_LaplacianAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type TdivergenceType struct {
	XsdGoPkgHasAtts_DivergenceAttlist

}

type TgradType struct {
	XsdGoPkgHasAtts_GradAttlist

}

type TcurlType struct {
	XsdGoPkgHasAtts_CurlAttlist

}

type TlaplacianType struct {
	XsdGoPkgHasAtts_LaplacianAttlist

}

type XsdGoPkgHasElem_Divergence struct {
	Divergence *TdivergenceType `xml:"http://www.w3.org/1998/Math/MathML divergence"`
}

type XsdGoPkgHasElems_Divergence struct {
	Divergences []*TdivergenceType `xml:"http://www.w3.org/1998/Math/MathML divergence"`
}

type XsdGoPkgHasElem_Grad struct {
	Grad *TgradType `xml:"http://www.w3.org/1998/Math/MathML grad"`
}

type XsdGoPkgHasElems_Grad struct {
	Grads []*TgradType `xml:"http://www.w3.org/1998/Math/MathML grad"`
}

type XsdGoPkgHasElem_Curl struct {
	Curl *TcurlType `xml:"http://www.w3.org/1998/Math/MathML curl"`
}

type XsdGoPkgHasElems_Curl struct {
	Curls []*TcurlType `xml:"http://www.w3.org/1998/Math/MathML curl"`
}

type XsdGoPkgHasElems_Laplacian struct {
	Laplacians []*TlaplacianType `xml:"http://www.w3.org/1998/Math/MathML laplacian"`
}

type XsdGoPkgHasElem_Laplacian struct {
	Laplacian *TlaplacianType `xml:"http://www.w3.org/1998/Math/MathML laplacian"`
}

type XsdGoPkgHasGroup_ContentVectorCalculusClass struct {
	XsdGoPkgHasElem_Divergence

	XsdGoPkgHasElem_Grad

	XsdGoPkgHasElem_Curl

	XsdGoPkgHasElem_Laplacian

}
