//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/content/constants.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is the XML Schema module for the basic constants of MathML content.
//	Author: Stéphane Dalmas.
import (
)

type TConstantType struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasElems_Naturalnumbers struct {
	Naturalnumberses []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML naturalnumbers"`
}

type XsdGoPkgHasElem_Naturalnumbers struct {
	Naturalnumbers *TConstantType `xml:"http://www.w3.org/1998/Math/MathML naturalnumbers"`
}

type XsdGoPkgHasElem_Primes struct {
	Primes *TConstantType `xml:"http://www.w3.org/1998/Math/MathML primes"`
}

type XsdGoPkgHasElems_Primes struct {
	Primeses []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML primes"`
}

type XsdGoPkgHasElem_Integers struct {
	Integers *TConstantType `xml:"http://www.w3.org/1998/Math/MathML integers"`
}

type XsdGoPkgHasElems_Integers struct {
	Integerses []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML integers"`
}

type XsdGoPkgHasElem_Rationals struct {
	Rationals *TConstantType `xml:"http://www.w3.org/1998/Math/MathML rationals"`
}

type XsdGoPkgHasElems_Rationals struct {
	Rationalses []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML rationals"`
}

type XsdGoPkgHasElem_Reals struct {
	Reals *TConstantType `xml:"http://www.w3.org/1998/Math/MathML reals"`
}

type XsdGoPkgHasElems_Reals struct {
	Realses []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML reals"`
}

type XsdGoPkgHasElem_Complexes struct {
	Complexes *TConstantType `xml:"http://www.w3.org/1998/Math/MathML complexes"`
}

type XsdGoPkgHasElems_Complexes struct {
	Complexeses []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML complexes"`
}

type XsdGoPkgHasElems_Emptyset struct {
	Emptysets []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML emptyset"`
}

type XsdGoPkgHasElem_Emptyset struct {
	Emptyset *TConstantType `xml:"http://www.w3.org/1998/Math/MathML emptyset"`
}

type XsdGoPkgHasElem_Exponentiale struct {
	Exponentiale *TConstantType `xml:"http://www.w3.org/1998/Math/MathML exponentiale"`
}

type XsdGoPkgHasElems_Exponentiale struct {
	Exponentiales []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML exponentiale"`
}

type XsdGoPkgHasElem_Imaginaryi struct {
	Imaginaryi *TConstantType `xml:"http://www.w3.org/1998/Math/MathML imaginaryi"`
}

type XsdGoPkgHasElems_Imaginaryi struct {
	Imaginaryis []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML imaginaryi"`
}

type XsdGoPkgHasElems_Pi struct {
	Pis []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML pi"`
}

type XsdGoPkgHasElem_Pi struct {
	Pi *TConstantType `xml:"http://www.w3.org/1998/Math/MathML pi"`
}

type XsdGoPkgHasElems_Eulergamma struct {
	Eulergammas []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML eulergamma"`
}

type XsdGoPkgHasElem_Eulergamma struct {
	Eulergamma *TConstantType `xml:"http://www.w3.org/1998/Math/MathML eulergamma"`
}

type XsdGoPkgHasElem_True struct {
	True *TConstantType `xml:"http://www.w3.org/1998/Math/MathML true"`
}

type XsdGoPkgHasElems_True struct {
	Trues []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML true"`
}

type XsdGoPkgHasElems_False struct {
	Falses []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML false"`
}

type XsdGoPkgHasElem_False struct {
	False *TConstantType `xml:"http://www.w3.org/1998/Math/MathML false"`
}

type XsdGoPkgHasElem_Infinity struct {
	Infinity *TConstantType `xml:"http://www.w3.org/1998/Math/MathML infinity"`
}

type XsdGoPkgHasElems_Infinity struct {
	Infinities []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML infinity"`
}

type XsdGoPkgHasElem_Notanumber struct {
	Notanumber *TConstantType `xml:"http://www.w3.org/1998/Math/MathML notanumber"`
}

type XsdGoPkgHasElems_Notanumber struct {
	Notanumbers []*TConstantType `xml:"http://www.w3.org/1998/Math/MathML notanumber"`
}

type XsdGoPkgHasGroup_ContentConstantsClass struct {
	XsdGoPkgHasElem_Naturalnumbers

	XsdGoPkgHasElem_Primes

	XsdGoPkgHasElem_Integers

	XsdGoPkgHasElem_Rationals

	XsdGoPkgHasElem_Reals

	XsdGoPkgHasElem_Complexes

	XsdGoPkgHasElem_Emptyset

	XsdGoPkgHasElem_Exponentiale

	XsdGoPkgHasElem_Imaginaryi

	XsdGoPkgHasElem_Pi

	XsdGoPkgHasElem_Eulergamma

	XsdGoPkgHasElem_True

	XsdGoPkgHasElem_False

	XsdGoPkgHasElem_Infinity

	XsdGoPkgHasElem_Notanumber

}
