//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/content/elementary-functions.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is an XML Schema module for the elementary functions in content
//	MathML.
//	Author: Stéphane Dalmas, INRIA.
import (
)

type TElementaryFunctionsType struct {
	XsdGoPkgHasAtts_CommonAttrib

	XsdGoPkgHasAtts_DefinitionAttrib

}

type TlogbaseType struct {
	XsdGoPkgHasGroup_LogbaseContent

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasElem_Exp struct {
	Exp *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML exp"`
}

type XsdGoPkgHasElems_Exp struct {
	Exps []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML exp"`
}

type XsdGoPkgHasElem_Ln struct {
	Ln *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML ln"`
}

type XsdGoPkgHasElems_Ln struct {
	Lns []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML ln"`
}

type XsdGoPkgHasElem_Log struct {
	Log *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML log"`
}

type XsdGoPkgHasElems_Log struct {
	Logs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML log"`
}

type XsdGoPkgHasElems_Logbase struct {
	Logbases []*TlogbaseType `xml:"http://www.w3.org/1998/Math/MathML logbase"`
}

type XsdGoPkgHasElem_Logbase struct {
	Logbase *TlogbaseType `xml:"http://www.w3.org/1998/Math/MathML logbase"`
}

type XsdGoPkgHasElem_Sin struct {
	Sin *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML sin"`
}

type XsdGoPkgHasElems_Sin struct {
	Sins []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML sin"`
}

type XsdGoPkgHasElems_Cos struct {
	Coses []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML cos"`
}

type XsdGoPkgHasElem_Cos struct {
	Cos *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML cos"`
}

type XsdGoPkgHasElem_Tan struct {
	Tan *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML tan"`
}

type XsdGoPkgHasElems_Tan struct {
	Tans []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML tan"`
}

type XsdGoPkgHasElem_Sec struct {
	Sec *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML sec"`
}

type XsdGoPkgHasElems_Sec struct {
	Secs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML sec"`
}

type XsdGoPkgHasElems_Csc struct {
	Cscs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML csc"`
}

type XsdGoPkgHasElem_Csc struct {
	Csc *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML csc"`
}

type XsdGoPkgHasElem_Cot struct {
	Cot *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML cot"`
}

type XsdGoPkgHasElems_Cot struct {
	Cots []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML cot"`
}

type XsdGoPkgHasElems_Arcsin struct {
	Arcsins []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arcsin"`
}

type XsdGoPkgHasElem_Arcsin struct {
	Arcsin *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arcsin"`
}

type XsdGoPkgHasElems_Arccos struct {
	Arccoses []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccos"`
}

type XsdGoPkgHasElem_Arccos struct {
	Arccos *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccos"`
}

type XsdGoPkgHasElem_Arctan struct {
	Arctan *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arctan"`
}

type XsdGoPkgHasElems_Arctan struct {
	Arctans []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arctan"`
}

type XsdGoPkgHasElems_Arccot struct {
	Arccots []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccot"`
}

type XsdGoPkgHasElem_Arccot struct {
	Arccot *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccot"`
}

type XsdGoPkgHasElems_Arccsc struct {
	Arccscs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccsc"`
}

type XsdGoPkgHasElem_Arccsc struct {
	Arccsc *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccsc"`
}

type XsdGoPkgHasElem_Arcsec struct {
	Arcsec *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arcsec"`
}

type XsdGoPkgHasElems_Arcsec struct {
	Arcsecs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arcsec"`
}

type XsdGoPkgHasElems_Sinh struct {
	Sinhs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML sinh"`
}

type XsdGoPkgHasElem_Sinh struct {
	Sinh *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML sinh"`
}

type XsdGoPkgHasElems_Cosh struct {
	Coshs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML cosh"`
}

type XsdGoPkgHasElem_Cosh struct {
	Cosh *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML cosh"`
}

type XsdGoPkgHasElem_Tanh struct {
	Tanh *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML tanh"`
}

type XsdGoPkgHasElems_Tanh struct {
	Tanhs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML tanh"`
}

type XsdGoPkgHasElem_Sech struct {
	Sech *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML sech"`
}

type XsdGoPkgHasElems_Sech struct {
	Sechs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML sech"`
}

type XsdGoPkgHasElem_Csch struct {
	Csch *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML csch"`
}

type XsdGoPkgHasElems_Csch struct {
	Cschs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML csch"`
}

type XsdGoPkgHasElem_Coth struct {
	Coth *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML coth"`
}

type XsdGoPkgHasElems_Coth struct {
	Coths []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML coth"`
}

type XsdGoPkgHasElems_Arccosh struct {
	Arccoshs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccosh"`
}

type XsdGoPkgHasElem_Arccosh struct {
	Arccosh *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccosh"`
}

type XsdGoPkgHasElems_Arccoth struct {
	Arccoths []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccoth"`
}

type XsdGoPkgHasElem_Arccoth struct {
	Arccoth *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccoth"`
}

type XsdGoPkgHasElems_Arccsch struct {
	Arccschs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccsch"`
}

type XsdGoPkgHasElem_Arccsch struct {
	Arccsch *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arccsch"`
}

type XsdGoPkgHasElem_Arcsech struct {
	Arcsech *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arcsech"`
}

type XsdGoPkgHasElems_Arcsech struct {
	Arcsechs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arcsech"`
}

type XsdGoPkgHasElems_Arcsinh struct {
	Arcsinhs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arcsinh"`
}

type XsdGoPkgHasElem_Arcsinh struct {
	Arcsinh *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arcsinh"`
}

type XsdGoPkgHasElems_Arctanh struct {
	Arctanhs []*TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arctanh"`
}

type XsdGoPkgHasElem_Arctanh struct {
	Arctanh *TElementaryFunctionsType `xml:"http://www.w3.org/1998/Math/MathML arctanh"`
}

type XsdGoPkgHasGroup_LogbaseContent struct {
	XsdGoPkgHasGroup_ContentExprClass

}

type XsdGoPkgHasGroup_ContentElementaryFunctionsClass struct {
	XsdGoPkgHasElem_Exp

	XsdGoPkgHasElem_Ln

	XsdGoPkgHasElem_Log

	XsdGoPkgHasElem_Logbase

	XsdGoPkgHasElem_Sin

	XsdGoPkgHasElem_Cos

	XsdGoPkgHasElem_Tan

	XsdGoPkgHasElem_Sec

	XsdGoPkgHasElem_Csc

	XsdGoPkgHasElem_Cot

	XsdGoPkgHasElem_Arcsin

	XsdGoPkgHasElem_Arccos

	XsdGoPkgHasElem_Arctan

	XsdGoPkgHasElem_Arcsec

	XsdGoPkgHasElem_Arccsc

	XsdGoPkgHasElem_Arccot

	XsdGoPkgHasElem_Sinh

	XsdGoPkgHasElem_Cosh

	XsdGoPkgHasElem_Tanh

	XsdGoPkgHasElem_Sech

	XsdGoPkgHasElem_Csch

	XsdGoPkgHasElem_Coth

	XsdGoPkgHasElem_Arccosh

	XsdGoPkgHasElem_Arccoth

	XsdGoPkgHasElem_Arccsch

	XsdGoPkgHasElem_Arcsech

	XsdGoPkgHasElem_Arcsinh

	XsdGoPkgHasElem_Arctanh

}
