//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/content/semantics.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is an XML Schema module for the "sematics" element of content MathML.
//	Author: Stéphane Dalmas, INRIA.
import (
)

type XsdGoPkgHasAtts_AnnotationAttlist struct {
	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_AnnotationXmlAttlist struct {
	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_SemanticsAttlist struct {
	XsdGoPkgHasAtts_CommonAttrib

}

type TannotationType struct {
	XsdGoPkgHasCdata

	XsdGoPkgHasAtts_AnnotationAttlist

}

type TannotationXmlType struct {
	XsdGoPkgHasGroup_AnnotationXmlContent

	XsdGoPkgHasAtts_AnnotationXmlAttlist

}

type TsemanticsType struct {
	XsdGoPkgHasGroup_SemanticsContent

	XsdGoPkgHasAtts_SemanticsAttlist

}

type XsdGoPkgHasElems_Annotation struct {
	Annotations []*TannotationType `xml:"http://www.w3.org/1998/Math/MathML annotation"`
}

type XsdGoPkgHasElem_Annotation struct {
	Annotation *TannotationType `xml:"http://www.w3.org/1998/Math/MathML annotation"`
}

type XsdGoPkgHasElems_AnnotationXml struct {
	AnnotationXmls []*TannotationXmlType `xml:"http://www.w3.org/1998/Math/MathML annotation-xml"`
}

type XsdGoPkgHasElem_AnnotationXml struct {
	AnnotationXml *TannotationXmlType `xml:"http://www.w3.org/1998/Math/MathML annotation-xml"`
}

type XsdGoPkgHasElem_Semantics struct {
	Semantics *TsemanticsType `xml:"http://www.w3.org/1998/Math/MathML semantics"`
}

type XsdGoPkgHasElems_Semantics struct {
	Semanticses []*TsemanticsType `xml:"http://www.w3.org/1998/Math/MathML semantics"`
}

type XsdGoPkgHasGroup_AnnotationXmlContent struct {
}

type XsdGoPkgHasGroup_AnnotationClass struct {
	XsdGoPkgHasElems_Annotation

	XsdGoPkgHasElems_AnnotationXml

}

type XsdGoPkgHasGroup_SemanticsContent struct {
	XsdGoPkgHasGroup_ContentExprClass

	XsdGoPkgHasGroup_AnnotationClass

}
