//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/content/functions.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is an XML Schema module for operators dealing with functions in content
//	MathML.
//	Author: Stéphane Dalmas, INRIA.
import (
)

type TFunctionsType struct {
	XsdGoPkgHasAtts_CommonAttrib

	XsdGoPkgHasAtts_DefinitionAttrib

}

type TdomainofapplicationType struct {
	XsdGoPkgHasGroup_DomainofapplicationContent

	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasElems_Compose struct {
	Composes []*TFunctionsType `xml:"http://www.w3.org/1998/Math/MathML compose"`
}

type XsdGoPkgHasElem_Compose struct {
	Compose *TFunctionsType `xml:"http://www.w3.org/1998/Math/MathML compose"`
}

type XsdGoPkgHasElem_Domain struct {
	Domain *TFunctionsType `xml:"http://www.w3.org/1998/Math/MathML domain"`
}

type XsdGoPkgHasElems_Domain struct {
	Domains []*TFunctionsType `xml:"http://www.w3.org/1998/Math/MathML domain"`
}

type XsdGoPkgHasElem_Codomain struct {
	Codomain *TFunctionsType `xml:"http://www.w3.org/1998/Math/MathML codomain"`
}

type XsdGoPkgHasElems_Codomain struct {
	Codomains []*TFunctionsType `xml:"http://www.w3.org/1998/Math/MathML codomain"`
}

type XsdGoPkgHasElem_Image struct {
	Image *TFunctionsType `xml:"http://www.w3.org/1998/Math/MathML image"`
}

type XsdGoPkgHasElems_Image struct {
	Images []*TFunctionsType `xml:"http://www.w3.org/1998/Math/MathML image"`
}

type XsdGoPkgHasElem_Domainofapplication struct {
	Domainofapplication *TdomainofapplicationType `xml:"http://www.w3.org/1998/Math/MathML domainofapplication"`
}

type XsdGoPkgHasElems_Domainofapplication struct {
	Domainofapplications []*TdomainofapplicationType `xml:"http://www.w3.org/1998/Math/MathML domainofapplication"`
}

type XsdGoPkgHasElems_Ident struct {
	Idents []*TFunctionsType `xml:"http://www.w3.org/1998/Math/MathML ident"`
}

type XsdGoPkgHasElem_Ident struct {
	Ident *TFunctionsType `xml:"http://www.w3.org/1998/Math/MathML ident"`
}

type XsdGoPkgHasGroup_DomainofapplicationContent struct {
	XsdGoPkgHasGroup_ContentExprClass

}

type XsdGoPkgHasGroup_ContentFunctionsClass struct {
	XsdGoPkgHasElem_Compose

	XsdGoPkgHasElem_Domain

	XsdGoPkgHasElem_Codomain

	XsdGoPkgHasElem_Image

	XsdGoPkgHasElem_Domainofapplication

	XsdGoPkgHasElem_Ident

}
