//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/content/sets.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is an XML Schema module for the part of content MathML dealing with
//	sets and lists.
//	Author: Stéphane Dalmas, INRIA.
import (
	xsdt "github.com/metaleap/go-xsd/types"
)

type XsdGoPkgHasAtts_SetAttlist struct {
	XsdGoPkgHasAtts_CommonAttrib

}

type TxsdListAttlistOrder xsdt.String

//	Since TxsdListAttlistOrder is just a simple String type, this merely sets the current value from the specified string.
func (me *TxsdListAttlistOrder) SetFromString (s string) { (*xsdt.String)(me).SetFromString(s) }

//	Since TxsdListAttlistOrder is just a simple String type, this merely returns the current string value.
func (me TxsdListAttlistOrder) String () string { return xsdt.String(me).String() }

//	This convenience method just performs a simple type conversion to TxsdListAttlistOrder's alias type xsdt.String
func (me TxsdListAttlistOrder) ToXsdtString () xsdt.String { return xsdt.String(me) }

//	Returns true if the value of this enumerated TxsdListAttlistOrder is "lexicographic".
func (me TxsdListAttlistOrder) IsLexicographic () bool { return me == "lexicographic" }

//	Returns true if the value of this enumerated TxsdListAttlistOrder is "numeric".
func (me TxsdListAttlistOrder) IsNumeric () bool { return me == "numeric" }

type XsdGoPkgHasAttr_Order_TxsdListAttlistOrder_ struct {
	Order TxsdListAttlistOrder `xml:"http://www.w3.org/1998/Math/MathML order,attr"`
}

type XsdGoPkgHasAtts_ListAttlist struct {
	XsdGoPkgHasAtts_CommonAttrib

	XsdGoPkgHasAttr_Order_TxsdListAttlistOrder_
}

type XsdGoPkgHasAtts_UnionAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_IntersectAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_InAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_NotinAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_SubsetAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_PrsubsetAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_NotsubsetAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_NotprsubsetAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_SetdiffAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_CardAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_CartesianproductAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type TsetType struct {
	XsdGoPkgHasGroup_SetContent

	XsdGoPkgHasAtts_SetAttlist

}

type TlistType struct {
	XsdGoPkgHasGroup_ListContent

	XsdGoPkgHasAtts_ListAttlist

}

type TunionType struct {
	XsdGoPkgHasAtts_UnionAttlist

}

type TintersectType struct {
	XsdGoPkgHasAtts_IntersectAttlist

}

type TinType struct {
	XsdGoPkgHasAtts_InAttlist

}

type TnotinType struct {
	XsdGoPkgHasAtts_NotinAttlist

}

type TsubsetType struct {
	XsdGoPkgHasAtts_SubsetAttlist

}

type TprsubsetType struct {
	XsdGoPkgHasAtts_PrsubsetAttlist

}

type TnotsubsetType struct {
	XsdGoPkgHasAtts_NotsubsetAttlist

}

type TnotprsubsetType struct {
	XsdGoPkgHasAtts_NotprsubsetAttlist

}

type TsetdiffType struct {
	XsdGoPkgHasAtts_SetdiffAttlist

}

type TcardType struct {
	XsdGoPkgHasAtts_CardAttlist

}

type TcartesianproductType struct {
	XsdGoPkgHasAtts_CartesianproductAttlist

}

type XsdGoPkgHasElems_Set struct {
	Sets []*TsetType `xml:"http://www.w3.org/1998/Math/MathML set"`
}

type XsdGoPkgHasElem_Set struct {
	Set *TsetType `xml:"http://www.w3.org/1998/Math/MathML set"`
}

type XsdGoPkgHasElem_List struct {
	List *TlistType `xml:"http://www.w3.org/1998/Math/MathML list"`
}

type XsdGoPkgHasElems_List struct {
	Lists []*TlistType `xml:"http://www.w3.org/1998/Math/MathML list"`
}

type XsdGoPkgHasElem_Union struct {
	Union *TunionType `xml:"http://www.w3.org/1998/Math/MathML union"`
}

type XsdGoPkgHasElems_Union struct {
	Unions []*TunionType `xml:"http://www.w3.org/1998/Math/MathML union"`
}

type XsdGoPkgHasElems_Intersect struct {
	Intersects []*TintersectType `xml:"http://www.w3.org/1998/Math/MathML intersect"`
}

type XsdGoPkgHasElem_Intersect struct {
	Intersect *TintersectType `xml:"http://www.w3.org/1998/Math/MathML intersect"`
}

type XsdGoPkgHasElems_In struct {
	Ins []*TinType `xml:"http://www.w3.org/1998/Math/MathML in"`
}

type XsdGoPkgHasElem_In struct {
	In *TinType `xml:"http://www.w3.org/1998/Math/MathML in"`
}

type XsdGoPkgHasElem_Notin struct {
	Notin *TnotinType `xml:"http://www.w3.org/1998/Math/MathML notin"`
}

type XsdGoPkgHasElems_Notin struct {
	Notins []*TnotinType `xml:"http://www.w3.org/1998/Math/MathML notin"`
}

type XsdGoPkgHasElem_Subset struct {
	Subset *TsubsetType `xml:"http://www.w3.org/1998/Math/MathML subset"`
}

type XsdGoPkgHasElems_Subset struct {
	Subsets []*TsubsetType `xml:"http://www.w3.org/1998/Math/MathML subset"`
}

type XsdGoPkgHasElem_Prsubset struct {
	Prsubset *TprsubsetType `xml:"http://www.w3.org/1998/Math/MathML prsubset"`
}

type XsdGoPkgHasElems_Prsubset struct {
	Prsubsets []*TprsubsetType `xml:"http://www.w3.org/1998/Math/MathML prsubset"`
}

type XsdGoPkgHasElems_Notsubset struct {
	Notsubsets []*TnotsubsetType `xml:"http://www.w3.org/1998/Math/MathML notsubset"`
}

type XsdGoPkgHasElem_Notsubset struct {
	Notsubset *TnotsubsetType `xml:"http://www.w3.org/1998/Math/MathML notsubset"`
}

type XsdGoPkgHasElem_Notprsubset struct {
	Notprsubset *TnotprsubsetType `xml:"http://www.w3.org/1998/Math/MathML notprsubset"`
}

type XsdGoPkgHasElems_Notprsubset struct {
	Notprsubsets []*TnotprsubsetType `xml:"http://www.w3.org/1998/Math/MathML notprsubset"`
}

type XsdGoPkgHasElem_Setdiff struct {
	Setdiff *TsetdiffType `xml:"http://www.w3.org/1998/Math/MathML setdiff"`
}

type XsdGoPkgHasElems_Setdiff struct {
	Setdiffs []*TsetdiffType `xml:"http://www.w3.org/1998/Math/MathML setdiff"`
}

type XsdGoPkgHasElems_Card struct {
	Cards []*TcardType `xml:"http://www.w3.org/1998/Math/MathML card"`
}

type XsdGoPkgHasElem_Card struct {
	Card *TcardType `xml:"http://www.w3.org/1998/Math/MathML card"`
}

type XsdGoPkgHasElems_Cartesianproduct struct {
	Cartesianproducts []*TcartesianproductType `xml:"http://www.w3.org/1998/Math/MathML cartesianproduct"`
}

type XsdGoPkgHasElem_Cartesianproduct struct {
	Cartesianproduct *TcartesianproductType `xml:"http://www.w3.org/1998/Math/MathML cartesianproduct"`
}

type XsdGoPkgHasGroup_SetContent struct {
	XsdGoPkgHasGroup_ContentExprClass

}

type XsdGoPkgHasGroup_ListContent struct {
	XsdGoPkgHasGroup_ContentExprClass

}

type XsdGoPkgHasGroup_ContentSetsClass struct {
	XsdGoPkgHasElem_Set

	XsdGoPkgHasElem_List

	XsdGoPkgHasElem_Union

	XsdGoPkgHasElem_Intersect

	XsdGoPkgHasElem_In

	XsdGoPkgHasElem_Notin

	XsdGoPkgHasElem_Subset

	XsdGoPkgHasElem_Prsubset

	XsdGoPkgHasElem_Notsubset

	XsdGoPkgHasElem_Notprsubset

	XsdGoPkgHasElem_Setdiff

	XsdGoPkgHasElem_Card

	XsdGoPkgHasElem_Cartesianproduct

}
