//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/content/statistics.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is an XML Schema module for the statistical operators of content MathML.
//	Author: Stéphane Dalmas, INRIA.
import (
)

type XsdGoPkgHasAtts_MeanAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_SdevAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_VarianceAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_MedianAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_ModeAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_MomentAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_MomentaboutAttlist struct {
	XsdGoPkgHasAtts_DefinitionAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type TmeanType struct {
	XsdGoPkgHasAtts_MeanAttlist

}

type TsdevType struct {
	XsdGoPkgHasAtts_SdevAttlist

}

type TvarianceType struct {
	XsdGoPkgHasAtts_VarianceAttlist

}

type TmedianType struct {
	XsdGoPkgHasAtts_MedianAttlist

}

type TmodeType struct {
	XsdGoPkgHasAtts_ModeAttlist

}

type TmomentType struct {
	XsdGoPkgHasAtts_MomentAttlist

}

type TmomentaboutType struct {
	XsdGoPkgHasGroup_MomentaboutContent

	XsdGoPkgHasAtts_MomentaboutAttlist

}

type XsdGoPkgHasElems_Mean struct {
	Means []*TmeanType `xml:"http://www.w3.org/1998/Math/MathML mean"`
}

type XsdGoPkgHasElem_Mean struct {
	Mean *TmeanType `xml:"http://www.w3.org/1998/Math/MathML mean"`
}

type XsdGoPkgHasElems_Sdev struct {
	Sdevs []*TsdevType `xml:"http://www.w3.org/1998/Math/MathML sdev"`
}

type XsdGoPkgHasElem_Sdev struct {
	Sdev *TsdevType `xml:"http://www.w3.org/1998/Math/MathML sdev"`
}

type XsdGoPkgHasElem_Variance struct {
	Variance *TvarianceType `xml:"http://www.w3.org/1998/Math/MathML variance"`
}

type XsdGoPkgHasElems_Variance struct {
	Variances []*TvarianceType `xml:"http://www.w3.org/1998/Math/MathML variance"`
}

type XsdGoPkgHasElems_Median struct {
	Medians []*TmedianType `xml:"http://www.w3.org/1998/Math/MathML median"`
}

type XsdGoPkgHasElem_Median struct {
	Median *TmedianType `xml:"http://www.w3.org/1998/Math/MathML median"`
}

type XsdGoPkgHasElem_Mode struct {
	Mode *TmodeType `xml:"http://www.w3.org/1998/Math/MathML mode"`
}

type XsdGoPkgHasElems_Mode struct {
	Modes []*TmodeType `xml:"http://www.w3.org/1998/Math/MathML mode"`
}

type XsdGoPkgHasElem_Moment struct {
	Moment *TmomentType `xml:"http://www.w3.org/1998/Math/MathML moment"`
}

type XsdGoPkgHasElems_Moment struct {
	Moments []*TmomentType `xml:"http://www.w3.org/1998/Math/MathML moment"`
}

type XsdGoPkgHasElem_Momentabout struct {
	Momentabout *TmomentaboutType `xml:"http://www.w3.org/1998/Math/MathML momentabout"`
}

type XsdGoPkgHasElems_Momentabout struct {
	Momentabouts []*TmomentaboutType `xml:"http://www.w3.org/1998/Math/MathML momentabout"`
}

type XsdGoPkgHasGroup_MomentaboutContent struct {
	XsdGoPkgHasGroup_ContentExprClass

}

type XsdGoPkgHasGroup_ContentStatisticsClass struct {
	XsdGoPkgHasElem_Mean

	XsdGoPkgHasElem_Sdev

	XsdGoPkgHasElem_Variance

	XsdGoPkgHasElem_Median

	XsdGoPkgHasElem_Mode

	XsdGoPkgHasElem_Moment

	XsdGoPkgHasElem_Momentabout

}
