//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/content/common-attrib.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is the XML schema module defining common attributes for the
//	content part of MathML.
//	Authors: Stéphane Dalmas, INRIA.
import (
	xsdt "github.com/metaleap/go-xsd/types"
)

type XsdGoPkgHasAttr_Encoding_XsdtString_ struct {
	Encoding xsdt.String `xml:"http://www.w3.org/1998/Math/MathML encoding,attr"`
}

type XsdGoPkgHasAttr_DefinitionURL_XsdtAnyURI_ struct {
	DefinitionURL xsdt.AnyURI `xml:"http://www.w3.org/1998/Math/MathML definitionURL,attr"`
}

type XsdGoPkgHasAtts_DefinitionAttrib struct {
	XsdGoPkgHasAttr_Encoding_XsdtString_
	XsdGoPkgHasAttr_DefinitionURL_XsdtAnyURI_
}
