//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/mathml2.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is an XML Schema for MathML.
//	Author: Stéphane Dalmas, INRIA.
import (
)

type XsdGoPkgHasCdata struct { CombinedCharDatas string `xml:",chardata"` }
