//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/presentation/tokens.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is the XML schema module for the token elements of the
//	presentation part of MathML.
//	Author: Stéphane Dalmas, INRIA.
import (
	xsdt "github.com/metaleap/go-xsd/types"
)

type XsdGoPkgHasAtts_MiAttlist struct {
	XsdGoPkgHasAtts_TokenStyleAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_MoAttlist struct {
	XsdGoPkgHasAtts_OperatorAttrib

	XsdGoPkgHasAtts_TokenStyleAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_MnAttlist struct {
	XsdGoPkgHasAtts_TokenStyleAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAtts_MtextAttlist struct {
	XsdGoPkgHasAtts_TokenStyleAttrib

	XsdGoPkgHasAtts_CommonAttrib

}

type XsdGoPkgHasAttr_Lquote_XsdtString_ struct {
	Lquote xsdt.String `xml:"http://www.w3.org/1998/Math/MathML lquote,attr"`
}

//	Returns the Default value for Lquote -- "\""
func (me *XsdGoPkgHasAttr_Lquote_XsdtString_) LquoteDefault () xsdt.String { return xsdt.String("\"") }

type XsdGoPkgHasAttr_Rquote_XsdtString_ struct {
	Rquote xsdt.String `xml:"http://www.w3.org/1998/Math/MathML rquote,attr"`
}

//	Returns the Default value for Rquote -- "\""
func (me *XsdGoPkgHasAttr_Rquote_XsdtString_) RquoteDefault () xsdt.String { return xsdt.String("\"") }

type XsdGoPkgHasAtts_MsAttlist struct {
	XsdGoPkgHasAtts_TokenStyleAttrib

	XsdGoPkgHasAtts_CommonAttrib

	XsdGoPkgHasAttr_Lquote_XsdtString_
	XsdGoPkgHasAttr_Rquote_XsdtString_
}

type TmiType struct {
	XsdGoPkgHasCdata

	XsdGoPkgHasGroup_GlyphAlignmarkClass

	XsdGoPkgHasAtts_MiAttlist

}

type TmoType struct {
	XsdGoPkgHasCdata

	XsdGoPkgHasGroup_GlyphAlignmarkClass

	XsdGoPkgHasAtts_MoAttlist

}

type TmnType struct {
	XsdGoPkgHasCdata

	XsdGoPkgHasGroup_GlyphAlignmarkClass

	XsdGoPkgHasAtts_MiAttlist

}

type TmtextType struct {
	XsdGoPkgHasCdata

	XsdGoPkgHasGroup_GlyphAlignmarkClass

	XsdGoPkgHasAtts_MtextAttlist

}

type TmsType struct {
	XsdGoPkgHasCdata

	XsdGoPkgHasGroup_GlyphAlignmarkClass

	XsdGoPkgHasAtts_MsAttlist

}

type XsdGoPkgHasElem_Mi struct {
	Mi *TmiType `xml:"http://www.w3.org/1998/Math/MathML mi"`
}

type XsdGoPkgHasElems_Mi struct {
	Mis []*TmiType `xml:"http://www.w3.org/1998/Math/MathML mi"`
}

type XsdGoPkgHasElem_Mo struct {
	Mo *TmoType `xml:"http://www.w3.org/1998/Math/MathML mo"`
}

type XsdGoPkgHasElems_Mo struct {
	Mos []*TmoType `xml:"http://www.w3.org/1998/Math/MathML mo"`
}

type XsdGoPkgHasElem_Mn struct {
	Mn *TmnType `xml:"http://www.w3.org/1998/Math/MathML mn"`
}

type XsdGoPkgHasElems_Mn struct {
	Mns []*TmnType `xml:"http://www.w3.org/1998/Math/MathML mn"`
}

type XsdGoPkgHasElem_Mtext struct {
	Mtext *TmtextType `xml:"http://www.w3.org/1998/Math/MathML mtext"`
}

type XsdGoPkgHasElems_Mtext struct {
	Mtexts []*TmtextType `xml:"http://www.w3.org/1998/Math/MathML mtext"`
}

type XsdGoPkgHasElem_Ms struct {
	Ms *TmsType `xml:"http://www.w3.org/1998/Math/MathML ms"`
}

type XsdGoPkgHasElems_Ms struct {
	Mses []*TmsType `xml:"http://www.w3.org/1998/Math/MathML ms"`
}

type XsdGoPkgHasGroup_GlyphAlignmarkClass struct {
	XsdGoPkgHasElem_Malignmark

	XsdGoPkgHasElem_Mglyph

}

type XsdGoPkgHasGroup_PresentationTokenClass struct {
	XsdGoPkgHasElem_Mi

	XsdGoPkgHasElem_Mo

	XsdGoPkgHasElem_Mn

	XsdGoPkgHasElem_Mtext

	XsdGoPkgHasElem_Ms

}
