//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/presentation/action.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is the XML Schema module for the MathML "maction" element.
//	Author: Stéphane Dalmas, INRIA.
import (
	xsdt "github.com/metaleap/go-xsd/types"
)

type XsdGoPkgHasAttr_Actiontype_XsdtString_ struct {
	Actiontype xsdt.String `xml:"http://www.w3.org/1998/Math/MathML actiontype,attr"`
}

type XsdGoPkgHasAttr_Selection_XsdtPositiveInteger_1 struct {
	Selection xsdt.PositiveInteger `xml:"http://www.w3.org/1998/Math/MathML selection,attr"`
}

//	Returns the Default value for Selection -- 1
func (me *XsdGoPkgHasAttr_Selection_XsdtPositiveInteger_1) SelectionDefault () xsdt.PositiveInteger { return xsdt.PositiveInteger(1) }

type XsdGoPkgHasAtts_MactionAttlist struct {
	XsdGoPkgHasAtts_CommonAttrib

	XsdGoPkgHasAttr_Actiontype_XsdtString_
	XsdGoPkgHasAttr_Selection_XsdtPositiveInteger_1
}

type TmactionType struct {
	XsdGoPkgHasGroup_MactionContent

	XsdGoPkgHasAtts_MactionAttlist

}

type XsdGoPkgHasElems_Maction struct {
	Mactions []*TmactionType `xml:"http://www.w3.org/1998/Math/MathML maction"`
}

type XsdGoPkgHasElem_Maction struct {
	Maction *TmactionType `xml:"http://www.w3.org/1998/Math/MathML maction"`
}

type XsdGoPkgHasGroup_MactionContent struct {
	XsdGoPkgHasGroup_PresentationExprClass

}
