//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/presentation/characters.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is the XML Schema module for the MathML "mglyph" element.
//	Author: Stéphane Dalmas, INRIA.
import (
	xsdt "github.com/metaleap/go-xsd/types"
)

type XsdGoPkgHasAttr_Alt_XsdtString_ struct {
	Alt xsdt.String `xml:"http://www.w3.org/1998/Math/MathML alt,attr"`
}

type XsdGoPkgHasAttr_Fontfamily_XsdtString_ struct {
	Fontfamily xsdt.String `xml:"http://www.w3.org/1998/Math/MathML fontfamily,attr"`
}

type XsdGoPkgHasAttr_Index_XsdtPositiveInteger_ struct {
	Index xsdt.PositiveInteger `xml:"http://www.w3.org/1998/Math/MathML index,attr"`
}

type XsdGoPkgHasAtts_MglyphAttlist struct {
	XsdGoPkgHasAttr_Alt_XsdtString_
	XsdGoPkgHasAttr_Fontfamily_XsdtString_
	XsdGoPkgHasAttr_Index_XsdtPositiveInteger_
}

type TmglyphType struct {
	XsdGoPkgHasAtts_MglyphAttlist

}

type XsdGoPkgHasElems_Mglyph struct {
	Mglyphs []*TmglyphType `xml:"http://www.w3.org/1998/Math/MathML mglyph"`
}

type XsdGoPkgHasElem_Mglyph struct {
	Mglyph *TmglyphType `xml:"http://www.w3.org/1998/Math/MathML mglyph"`
}
