//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		www.w3.org/Math/XMLSchema/mathml2/presentation/style.xsd
package gopkg_WwwW3OrgMathXMLSchemaMathml2Mathml2Xsd

//	This is an XML Schema for the "mstyle" element of MathML.
//	Author: Stéphane Dalmas, INRIA.
import (
	xsdt "github.com/metaleap/go-xsd/types"
)

type XsdGoPkgHasAttr_Scriptlevel_XsdtInteger_ struct {
	Scriptlevel xsdt.Integer `xml:"http://www.w3.org/1998/Math/MathML scriptlevel,attr"`
}

type XsdGoPkgHasAttr_Displaystyle_XsdtBoolean_ struct {
	Displaystyle xsdt.Boolean `xml:"http://www.w3.org/1998/Math/MathML displaystyle,attr"`
}

type XsdGoPkgHasAttr_Scriptsizemultiplier_XsdtDecimal_071 struct {
	Scriptsizemultiplier xsdt.Decimal `xml:"http://www.w3.org/1998/Math/MathML scriptsizemultiplier,attr"`
}

//	Returns the Default value for Scriptsizemultiplier -- "0.71"
func (me *XsdGoPkgHasAttr_Scriptsizemultiplier_XsdtDecimal_071) ScriptsizemultiplierDefault () xsdt.Decimal { return xsdt.Decimal("0.71") }

type XsdGoPkgHasAttr_Scriptminsize_TlengthWithUnit_8Pt struct {
	Scriptminsize TlengthWithUnit `xml:"http://www.w3.org/1998/Math/MathML scriptminsize,attr"`
}

//	Returns the Default value for Scriptminsize -- "8pt"
func (me *XsdGoPkgHasAttr_Scriptminsize_TlengthWithUnit_8Pt) ScriptminsizeDefault () TlengthWithUnit { return TlengthWithUnit("8pt") }

type XsdGoPkgHasAttr_Color_XsdtString_ struct {
	Color xsdt.String `xml:"http://www.w3.org/1998/Math/MathML color,attr"`
}

type XsdGoPkgHasAttr_Background_XsdtString_Transparent struct {
	Background xsdt.String `xml:"http://www.w3.org/1998/Math/MathML background,attr"`
}

//	Returns the Default value for Background -- "transparent"
func (me *XsdGoPkgHasAttr_Background_XsdtString_Transparent) BackgroundDefault () xsdt.String { return xsdt.String("transparent") }

type XsdGoPkgHasAttr_Veryverythinmathspace_TlengthWithUnit_00555556Em struct {
	Veryverythinmathspace TlengthWithUnit `xml:"http://www.w3.org/1998/Math/MathML veryverythinmathspace,attr"`
}

//	Returns the Default value for Veryverythinmathspace -- "0.0555556em"
func (me *XsdGoPkgHasAttr_Veryverythinmathspace_TlengthWithUnit_00555556Em) VeryverythinmathspaceDefault () TlengthWithUnit { return TlengthWithUnit("0.0555556em") }

type XsdGoPkgHasAttr_Verythinmathspace_TlengthWithUnit_0111111Em struct {
	Verythinmathspace TlengthWithUnit `xml:"http://www.w3.org/1998/Math/MathML verythinmathspace,attr"`
}

//	Returns the Default value for Verythinmathspace -- "0.111111em"
func (me *XsdGoPkgHasAttr_Verythinmathspace_TlengthWithUnit_0111111Em) VerythinmathspaceDefault () TlengthWithUnit { return TlengthWithUnit("0.111111em") }

type XsdGoPkgHasAttr_Thinmathspace_TlengthWithUnit_0166667Em struct {
	Thinmathspace TlengthWithUnit `xml:"http://www.w3.org/1998/Math/MathML thinmathspace,attr"`
}

//	Returns the Default value for Thinmathspace -- "0.166667em"
func (me *XsdGoPkgHasAttr_Thinmathspace_TlengthWithUnit_0166667Em) ThinmathspaceDefault () TlengthWithUnit { return TlengthWithUnit("0.166667em") }

type XsdGoPkgHasAttr_Mediummathspace_TlengthWithUnit_0222222Em struct {
	Mediummathspace TlengthWithUnit `xml:"http://www.w3.org/1998/Math/MathML mediummathspace,attr"`
}

//	Returns the Default value for Mediummathspace -- "0.222222em"
func (me *XsdGoPkgHasAttr_Mediummathspace_TlengthWithUnit_0222222Em) MediummathspaceDefault () TlengthWithUnit { return TlengthWithUnit("0.222222em") }

type XsdGoPkgHasAttr_Thickmathspace_TlengthWithUnit_0277778Em struct {
	Thickmathspace TlengthWithUnit `xml:"http://www.w3.org/1998/Math/MathML thickmathspace,attr"`
}

//	Returns the Default value for Thickmathspace -- "0.277778em"
func (me *XsdGoPkgHasAttr_Thickmathspace_TlengthWithUnit_0277778Em) ThickmathspaceDefault () TlengthWithUnit { return TlengthWithUnit("0.277778em") }

type XsdGoPkgHasAttr_Verythickmathspace_TlengthWithUnit_0333333Em struct {
	Verythickmathspace TlengthWithUnit `xml:"http://www.w3.org/1998/Math/MathML verythickmathspace,attr"`
}

//	Returns the Default value for Verythickmathspace -- "0.333333em"
func (me *XsdGoPkgHasAttr_Verythickmathspace_TlengthWithUnit_0333333Em) VerythickmathspaceDefault () TlengthWithUnit { return TlengthWithUnit("0.333333em") }

type XsdGoPkgHasAttr_Veryverythickmathspace_TlengthWithUnit_0388889Em struct {
	Veryverythickmathspace TlengthWithUnit `xml:"http://www.w3.org/1998/Math/MathML veryverythickmathspace,attr"`
}

//	Returns the Default value for Veryverythickmathspace -- "0.388889em"
func (me *XsdGoPkgHasAttr_Veryverythickmathspace_TlengthWithUnit_0388889Em) VeryverythickmathspaceDefault () TlengthWithUnit { return TlengthWithUnit("0.388889em") }

type TxsdMstyleAttlistLinethickness xsdt.String

//	Since TxsdMstyleAttlistLinethickness is just a simple String type, this merely sets the current value from the specified string.
func (me *TxsdMstyleAttlistLinethickness) SetFromString (s string) { (*xsdt.String)(me).SetFromString(s) }

//	Since TxsdMstyleAttlistLinethickness is just a simple String type, this merely returns the current string value.
func (me TxsdMstyleAttlistLinethickness) String () string { return xsdt.String(me).String() }

//	This convenience method just performs a simple type conversion to TxsdMstyleAttlistLinethickness's alias type xsdt.String
func (me TxsdMstyleAttlistLinethickness) ToXsdtString () xsdt.String { return xsdt.String(me) }

//	TxsdMstyleAttlistLinethickness is an XSD union type of several types. This is a simple type conversion to TlengthWithOptionalUnit, but keep in mind the actual value may or may not be a valid TlengthWithOptionalUnit value.
func (me TxsdMstyleAttlistLinethickness) ToTlengthWithOptionalUnit () TlengthWithOptionalUnit { return TlengthWithOptionalUnit(me) }

//	TxsdMstyleAttlistLinethickness is an XSD union type of several types. This is a simple type conversion to Tthickness, but keep in mind the actual value may or may not be a valid Tthickness value.
func (me TxsdMstyleAttlistLinethickness) ToTthickness () Tthickness { return Tthickness(me) }

type XsdGoPkgHasAttr_Linethickness_TxsdMstyleAttlistLinethickness_1 struct {
	Linethickness TxsdMstyleAttlistLinethickness `xml:"http://www.w3.org/1998/Math/MathML linethickness,attr"`
}

//	Returns the Default value for Linethickness -- "1"
func (me *XsdGoPkgHasAttr_Linethickness_TxsdMstyleAttlistLinethickness_1) LinethicknessDefault () TxsdMstyleAttlistLinethickness { return TxsdMstyleAttlistLinethickness("1") }

type XsdGoPkgHasAtts_MstyleAttlist struct {
	XsdGoPkgHasAtts_OperatorAttrib

	XsdGoPkgHasAtts_TokenStyleAttrib

	XsdGoPkgHasAtts_CommonAttrib

	XsdGoPkgHasAttr_Scriptlevel_XsdtInteger_
	XsdGoPkgHasAttr_Displaystyle_XsdtBoolean_
	XsdGoPkgHasAttr_Scriptsizemultiplier_XsdtDecimal_071
	XsdGoPkgHasAttr_Scriptminsize_TlengthWithUnit_8Pt
	XsdGoPkgHasAttr_Color_XsdtString_
	XsdGoPkgHasAttr_Background_XsdtString_Transparent
	XsdGoPkgHasAttr_Veryverythinmathspace_TlengthWithUnit_00555556Em
	XsdGoPkgHasAttr_Verythinmathspace_TlengthWithUnit_0111111Em
	XsdGoPkgHasAttr_Thinmathspace_TlengthWithUnit_0166667Em
	XsdGoPkgHasAttr_Mediummathspace_TlengthWithUnit_0222222Em
	XsdGoPkgHasAttr_Thickmathspace_TlengthWithUnit_0277778Em
	XsdGoPkgHasAttr_Verythickmathspace_TlengthWithUnit_0333333Em
	XsdGoPkgHasAttr_Veryverythickmathspace_TlengthWithUnit_0388889Em
	XsdGoPkgHasAttr_Linethickness_TxsdMstyleAttlistLinethickness_1
}

type TmstyleType struct {
	XsdGoPkgHasGroup_MstyleContent

	XsdGoPkgHasAtts_MstyleAttlist

}

type XsdGoPkgHasElems_Mstyle struct {
	Mstyles []*TmstyleType `xml:"http://www.w3.org/1998/Math/MathML mstyle"`
}

type XsdGoPkgHasElem_Mstyle struct {
	Mstyle *TmstyleType `xml:"http://www.w3.org/1998/Math/MathML mstyle"`
}

type XsdGoPkgHasGroup_MstyleContent struct {
	XsdGoPkgHasGroup_PresentationExprClass

}
