//	Auto-generated by the "go-xsd" package located at:
//		github.com/metaleap/go-xsd
//	Comments on types and fields (if any) are from the XSD file located at:
//		kbcafe.com/rss/atom.xsd.xml
package gopkg_KbcafeComRssAtomXsdXml

//	This version of the Atom schema is based on version 1.0 of the format specifications,
//	found here http://www.atomenabled.org/developers/syndication/atom-format-spec.php.
//	An Atom document may have two root elements, feed and entry, as defined in section 2.
import (
	xml "github.com/metaleap/go-xsd/pkg/www.w3.org/2001/03/xml.xsd_gopkg"
	xsdt "github.com/metaleap/go-xsd/types"
)

type XsdGoPkgHasCdata struct { CombinedCharDatas string `xml:",chardata"` }

//	Schema definition for an email address.
type TemailType xsdt.NormalizedString

//	Since TemailType is just a simple String type, this merely sets the current value from the specified string.
func (me *TemailType) SetFromString (s string) { (*xsdt.NormalizedString)(me).SetFromString(s) }

//	Since TemailType is just a simple String type, this merely returns the current string value.
func (me TemailType) String () string { return xsdt.NormalizedString(me).String() }

//	This convenience method just performs a simple type conversion to TemailType's alias type xsdt.NormalizedString
func (me TemailType) ToXsdtNormalizedString () xsdt.NormalizedString { return xsdt.NormalizedString(me) }

type XsdGoPkgHasAtts_CommonAttributes struct {
	xml.XsdGoPkgHasAttr_Base
	xml.XsdGoPkgHasAttr_Lang
}

type TxsdTextTypeType xsdt.Token

//	Since TxsdTextTypeType is just a simple String type, this merely sets the current value from the specified string.
func (me *TxsdTextTypeType) SetFromString (s string) { (*xsdt.Token)(me).SetFromString(s) }

//	Since TxsdTextTypeType is just a simple String type, this merely returns the current string value.
func (me TxsdTextTypeType) String () string { return xsdt.Token(me).String() }

//	This convenience method just performs a simple type conversion to TxsdTextTypeType's alias type xsdt.Token
func (me TxsdTextTypeType) ToXsdtToken () xsdt.Token { return xsdt.Token(me) }

//	Returns true if the value of this enumerated TxsdTextTypeType is "text".
func (me TxsdTextTypeType) IsText () bool { return me == "text" }

//	Returns true if the value of this enumerated TxsdTextTypeType is "html".
func (me TxsdTextTypeType) IsHtml () bool { return me == "html" }

//	Returns true if the value of this enumerated TxsdTextTypeType is "xhtml".
func (me TxsdTextTypeType) IsXhtml () bool { return me == "xhtml" }

type XsdGoPkgHasAttr_Type_TxsdTextTypeType_ struct {
	Type TxsdTextTypeType `xml:"http://www.w3.org/2005/Atom type,attr"`
}

//	The Atom text construct is defined in section 3.1 of the format spec.
type TtextType struct {
	XsdGoPkgHasCdata

	XsdGoPkgHasAtts_CommonAttributes

	XsdGoPkgHasAttr_Type_TxsdTextTypeType_

}

type XsdGoPkgHasElem_namechoicepersonTypeschema_Name_XsdtString_ struct {
	Name xsdt.String `xml:"http://www.w3.org/2005/Atom name"`
}

type XsdGoPkgHasElems_namechoicepersonTypeschema_Name_XsdtString_ struct {
	Names []xsdt.String `xml:"http://www.w3.org/2005/Atom name"`
}

type XsdGoPkgHasElems_urichoicepersonTypeschema_Uri_TuriType_ struct {
	Uris []*TuriType `xml:"http://www.w3.org/2005/Atom uri"`
}

type XsdGoPkgHasElem_urichoicepersonTypeschema_Uri_TuriType_ struct {
	Uri *TuriType `xml:"http://www.w3.org/2005/Atom uri"`
}

type XsdGoPkgHasElems_emailchoicepersonTypeschema_Email_TemailType_ struct {
	Emails []TemailType `xml:"http://www.w3.org/2005/Atom email"`
}

type XsdGoPkgHasElem_emailchoicepersonTypeschema_Email_TemailType_ struct {
	Email TemailType `xml:"http://www.w3.org/2005/Atom email"`
}

//	The Atom person construct is defined in section 3.2 of the format spec.
type TpersonType struct {
	XsdGoPkgHasElems_namechoicepersonTypeschema_Name_XsdtString_

	XsdGoPkgHasElems_urichoicepersonTypeschema_Uri_TuriType_

	XsdGoPkgHasElems_emailchoicepersonTypeschema_Email_TemailType_

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElems_authorchoicefeedTypeschema_Author_TpersonType_ struct {
	Authors []*TpersonType `xml:"http://www.w3.org/2005/Atom author"`
}

type XsdGoPkgHasElem_authorchoicefeedTypeschema_Author_TpersonType_ struct {
	Author *TpersonType `xml:"http://www.w3.org/2005/Atom author"`
}

type XsdGoPkgHasElems_categorychoicefeedTypeschema_Category_TcategoryType_ struct {
	Categories []*TcategoryType `xml:"http://www.w3.org/2005/Atom category"`
}

type XsdGoPkgHasElem_categorychoicefeedTypeschema_Category_TcategoryType_ struct {
	Category *TcategoryType `xml:"http://www.w3.org/2005/Atom category"`
}

type XsdGoPkgHasElem_contributorchoicefeedTypeschema_Contributor_TpersonType_ struct {
	Contributor *TpersonType `xml:"http://www.w3.org/2005/Atom contributor"`
}

type XsdGoPkgHasElems_contributorchoicefeedTypeschema_Contributor_TpersonType_ struct {
	Contributors []*TpersonType `xml:"http://www.w3.org/2005/Atom contributor"`
}

type XsdGoPkgHasElem_generatorchoicefeedTypeschema_Generator_TgeneratorType_ struct {
	Generator *TgeneratorType `xml:"http://www.w3.org/2005/Atom generator"`
}

type XsdGoPkgHasElems_generatorchoicefeedTypeschema_Generator_TgeneratorType_ struct {
	Generators []*TgeneratorType `xml:"http://www.w3.org/2005/Atom generator"`
}

type XsdGoPkgHasElem_iconchoicefeedTypeschema_Icon_TiconType_ struct {
	Icon *TiconType `xml:"http://www.w3.org/2005/Atom icon"`
}

type XsdGoPkgHasElems_iconchoicefeedTypeschema_Icon_TiconType_ struct {
	Icons []*TiconType `xml:"http://www.w3.org/2005/Atom icon"`
}

type XsdGoPkgHasElem_idchoicefeedTypeschema_Id_TidType_ struct {
	Id *TidType `xml:"http://www.w3.org/2005/Atom id"`
}

type XsdGoPkgHasElems_idchoicefeedTypeschema_Id_TidType_ struct {
	Ids []*TidType `xml:"http://www.w3.org/2005/Atom id"`
}

type XsdGoPkgHasElem_linkchoicefeedTypeschema_Link_TlinkType_ struct {
	Link *TlinkType `xml:"http://www.w3.org/2005/Atom link"`
}

type XsdGoPkgHasElems_linkchoicefeedTypeschema_Link_TlinkType_ struct {
	Links []*TlinkType `xml:"http://www.w3.org/2005/Atom link"`
}

type XsdGoPkgHasElem_logochoicefeedTypeschema_Logo_TlogoType_ struct {
	Logo *TlogoType `xml:"http://www.w3.org/2005/Atom logo"`
}

type XsdGoPkgHasElems_logochoicefeedTypeschema_Logo_TlogoType_ struct {
	Logos []*TlogoType `xml:"http://www.w3.org/2005/Atom logo"`
}

type XsdGoPkgHasElem_rightschoicefeedTypeschema_Rights_TtextType_ struct {
	Rights *TtextType `xml:"http://www.w3.org/2005/Atom rights"`
}

type XsdGoPkgHasElems_rightschoicefeedTypeschema_Rights_TtextType_ struct {
	Rightses []*TtextType `xml:"http://www.w3.org/2005/Atom rights"`
}

type XsdGoPkgHasElem_subtitlechoicefeedTypeschema_Subtitle_TtextType_ struct {
	Subtitle *TtextType `xml:"http://www.w3.org/2005/Atom subtitle"`
}

type XsdGoPkgHasElems_subtitlechoicefeedTypeschema_Subtitle_TtextType_ struct {
	Subtitles []*TtextType `xml:"http://www.w3.org/2005/Atom subtitle"`
}

type XsdGoPkgHasElem_titlechoicefeedTypeschema_Title_TtextType_ struct {
	Title *TtextType `xml:"http://www.w3.org/2005/Atom title"`
}

type XsdGoPkgHasElems_titlechoicefeedTypeschema_Title_TtextType_ struct {
	Titles []*TtextType `xml:"http://www.w3.org/2005/Atom title"`
}

type XsdGoPkgHasElem_updatedchoicefeedTypeschema_Updated_TdateTimeType_ struct {
	Updated *TdateTimeType `xml:"http://www.w3.org/2005/Atom updated"`
}

type XsdGoPkgHasElems_updatedchoicefeedTypeschema_Updated_TdateTimeType_ struct {
	Updateds []*TdateTimeType `xml:"http://www.w3.org/2005/Atom updated"`
}

type XsdGoPkgHasElem_entrychoicefeedTypeschema_Entry_TentryType_ struct {
	Entry *TentryType `xml:"http://www.w3.org/2005/Atom entry"`
}

type XsdGoPkgHasElems_entrychoicefeedTypeschema_Entry_TentryType_ struct {
	Entries []*TentryType `xml:"http://www.w3.org/2005/Atom entry"`
}

//	The Atom feed construct is defined in section 4.1.1 of the format spec.
type TfeedType struct {
	XsdGoPkgHasElems_authorchoicefeedTypeschema_Author_TpersonType_

	XsdGoPkgHasElems_categorychoicefeedTypeschema_Category_TcategoryType_

	XsdGoPkgHasElems_contributorchoicefeedTypeschema_Contributor_TpersonType_

	XsdGoPkgHasElems_generatorchoicefeedTypeschema_Generator_TgeneratorType_

	XsdGoPkgHasElems_iconchoicefeedTypeschema_Icon_TiconType_

	XsdGoPkgHasElems_idchoicefeedTypeschema_Id_TidType_

	XsdGoPkgHasElems_linkchoicefeedTypeschema_Link_TlinkType_

	XsdGoPkgHasElems_logochoicefeedTypeschema_Logo_TlogoType_

	XsdGoPkgHasElems_rightschoicefeedTypeschema_Rights_TtextType_

	XsdGoPkgHasElems_subtitlechoicefeedTypeschema_Subtitle_TtextType_

	XsdGoPkgHasElems_titlechoicefeedTypeschema_Title_TtextType_

	XsdGoPkgHasElems_updatedchoicefeedTypeschema_Updated_TdateTimeType_

	XsdGoPkgHasElems_entrychoicefeedTypeschema_Entry_TentryType_

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElem_authorchoiceentryTypeschema_Author_TpersonType_ struct {
	Author *TpersonType `xml:"http://www.w3.org/2005/Atom author"`
}

type XsdGoPkgHasElems_authorchoiceentryTypeschema_Author_TpersonType_ struct {
	Authors []*TpersonType `xml:"http://www.w3.org/2005/Atom author"`
}

type XsdGoPkgHasElem_categorychoiceentryTypeschema_Category_TcategoryType_ struct {
	Category *TcategoryType `xml:"http://www.w3.org/2005/Atom category"`
}

type XsdGoPkgHasElems_categorychoiceentryTypeschema_Category_TcategoryType_ struct {
	Categories []*TcategoryType `xml:"http://www.w3.org/2005/Atom category"`
}

type XsdGoPkgHasElems_contentchoiceentryTypeschema_Content_TcontentType_ struct {
	Contents []*TcontentType `xml:"http://www.w3.org/2005/Atom content"`
}

type XsdGoPkgHasElem_contentchoiceentryTypeschema_Content_TcontentType_ struct {
	Content *TcontentType `xml:"http://www.w3.org/2005/Atom content"`
}

type XsdGoPkgHasElem_contributorchoiceentryTypeschema_Contributor_TpersonType_ struct {
	Contributor *TpersonType `xml:"http://www.w3.org/2005/Atom contributor"`
}

type XsdGoPkgHasElems_contributorchoiceentryTypeschema_Contributor_TpersonType_ struct {
	Contributors []*TpersonType `xml:"http://www.w3.org/2005/Atom contributor"`
}

type XsdGoPkgHasElem_idchoiceentryTypeschema_Id_TidType_ struct {
	Id *TidType `xml:"http://www.w3.org/2005/Atom id"`
}

type XsdGoPkgHasElems_idchoiceentryTypeschema_Id_TidType_ struct {
	Ids []*TidType `xml:"http://www.w3.org/2005/Atom id"`
}

type XsdGoPkgHasElems_linkchoiceentryTypeschema_Link_TlinkType_ struct {
	Links []*TlinkType `xml:"http://www.w3.org/2005/Atom link"`
}

type XsdGoPkgHasElem_linkchoiceentryTypeschema_Link_TlinkType_ struct {
	Link *TlinkType `xml:"http://www.w3.org/2005/Atom link"`
}

type XsdGoPkgHasElems_publishedchoiceentryTypeschema_Published_TdateTimeType_ struct {
	Publisheds []*TdateTimeType `xml:"http://www.w3.org/2005/Atom published"`
}

type XsdGoPkgHasElem_publishedchoiceentryTypeschema_Published_TdateTimeType_ struct {
	Published *TdateTimeType `xml:"http://www.w3.org/2005/Atom published"`
}

type XsdGoPkgHasElem_rightschoiceentryTypeschema_Rights_TtextType_ struct {
	Rights *TtextType `xml:"http://www.w3.org/2005/Atom rights"`
}

type XsdGoPkgHasElems_rightschoiceentryTypeschema_Rights_TtextType_ struct {
	Rightses []*TtextType `xml:"http://www.w3.org/2005/Atom rights"`
}

type XsdGoPkgHasElem_sourcechoiceentryTypeschema_Source_TtextType_ struct {
	Source *TtextType `xml:"http://www.w3.org/2005/Atom source"`
}

type XsdGoPkgHasElems_sourcechoiceentryTypeschema_Source_TtextType_ struct {
	Sources []*TtextType `xml:"http://www.w3.org/2005/Atom source"`
}

type XsdGoPkgHasElem_summarychoiceentryTypeschema_Summary_TtextType_ struct {
	Summary *TtextType `xml:"http://www.w3.org/2005/Atom summary"`
}

type XsdGoPkgHasElems_summarychoiceentryTypeschema_Summary_TtextType_ struct {
	Summaries []*TtextType `xml:"http://www.w3.org/2005/Atom summary"`
}

type XsdGoPkgHasElem_titlechoiceentryTypeschema_Title_TtextType_ struct {
	Title *TtextType `xml:"http://www.w3.org/2005/Atom title"`
}

type XsdGoPkgHasElems_titlechoiceentryTypeschema_Title_TtextType_ struct {
	Titles []*TtextType `xml:"http://www.w3.org/2005/Atom title"`
}

type XsdGoPkgHasElem_updatedchoiceentryTypeschema_Updated_TdateTimeType_ struct {
	Updated *TdateTimeType `xml:"http://www.w3.org/2005/Atom updated"`
}

type XsdGoPkgHasElems_updatedchoiceentryTypeschema_Updated_TdateTimeType_ struct {
	Updateds []*TdateTimeType `xml:"http://www.w3.org/2005/Atom updated"`
}

//	The Atom entry construct is defined in section 4.1.2 of the format spec.
type TentryType struct {
	XsdGoPkgHasElems_authorchoiceentryTypeschema_Author_TpersonType_

	XsdGoPkgHasElems_categorychoiceentryTypeschema_Category_TcategoryType_

	XsdGoPkgHasElems_contentchoiceentryTypeschema_Content_TcontentType_

	XsdGoPkgHasElems_contributorchoiceentryTypeschema_Contributor_TpersonType_

	XsdGoPkgHasElems_idchoiceentryTypeschema_Id_TidType_

	XsdGoPkgHasElems_linkchoiceentryTypeschema_Link_TlinkType_

	XsdGoPkgHasElems_publishedchoiceentryTypeschema_Published_TdateTimeType_

	XsdGoPkgHasElems_rightschoiceentryTypeschema_Rights_TtextType_

	XsdGoPkgHasElems_sourcechoiceentryTypeschema_Source_TtextType_

	XsdGoPkgHasElems_summarychoiceentryTypeschema_Summary_TtextType_

	XsdGoPkgHasElems_titlechoiceentryTypeschema_Title_TtextType_

	XsdGoPkgHasElems_updatedchoiceentryTypeschema_Updated_TdateTimeType_

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasAttr_Type_XsdtString_ struct {
	Type xsdt.String `xml:"http://www.w3.org/2005/Atom type,attr"`
}

type XsdGoPkgHasAttr_Src_XsdtAnyURI_ struct {
	Src xsdt.AnyURI `xml:"http://www.w3.org/2005/Atom src,attr"`
}

//	The Atom content construct is defined in section 4.1.3 of the format spec.
type TcontentType struct {
	XsdGoPkgHasCdata

	XsdGoPkgHasAtts_CommonAttributes

	XsdGoPkgHasAttr_Src_XsdtAnyURI_

	XsdGoPkgHasAttr_Type_XsdtString_

}

type XsdGoPkgHasAttr_Term_XsdtString_ struct {
	Term xsdt.String `xml:"http://www.w3.org/2005/Atom term,attr"`
}

type XsdGoPkgHasAttr_Scheme_XsdtAnyURI_ struct {
	Scheme xsdt.AnyURI `xml:"http://www.w3.org/2005/Atom scheme,attr"`
}

type XsdGoPkgHasAttr_Label_XsdtString_ struct {
	Label xsdt.String `xml:"http://www.w3.org/2005/Atom label,attr"`
}

//	The Atom cagegory construct is defined in section 4.2.2 of the format spec.
type TcategoryType struct {
	XsdGoPkgHasAtts_CommonAttributes

	XsdGoPkgHasAttr_Term_XsdtString_

	XsdGoPkgHasAttr_Label_XsdtString_

	XsdGoPkgHasAttr_Scheme_XsdtAnyURI_

}

type XsdGoPkgHasAttr_Uri_XsdtAnyURI_ struct {
	Uri xsdt.AnyURI `xml:"http://www.w3.org/2005/Atom uri,attr"`
}

type XsdGoPkgHasAttr_Version_XsdtString_ struct {
	Version xsdt.String `xml:"http://www.w3.org/2005/Atom version,attr"`
}

//	The Atom generator element is defined in section 4.2.4 of the format spec.
type TgeneratorType struct {
	XsdGoPkgValue xsdt.String `xml:",chardata"`

	XsdGoPkgHasAtts_CommonAttributes

	XsdGoPkgHasAttr_Version_XsdtString_

	XsdGoPkgHasAttr_Uri_XsdtAnyURI_

}

//	The Atom icon construct is defined in section 4.2.5 of the format spec.
type TiconType struct {
	XsdGoPkgValue xsdt.AnyURI `xml:",chardata"`

	XsdGoPkgHasAtts_CommonAttributes

}

//	The Atom id construct is defined in section 4.2.6 of the format spec.
type TidType struct {
	XsdGoPkgValue xsdt.AnyURI `xml:",chardata"`

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasAttr_Href_XsdtAnyURI_ struct {
	Href xsdt.AnyURI `xml:"http://www.w3.org/2005/Atom href,attr"`
}

type XsdGoPkgHasAttr_Rel_XsdtString_ struct {
	Rel xsdt.String `xml:"http://www.w3.org/2005/Atom rel,attr"`
}

type XsdGoPkgHasAttr_Hreflang_XsdtNmtoken_ struct {
	Hreflang xsdt.Nmtoken `xml:"http://www.w3.org/2005/Atom hreflang,attr"`
}

type XsdGoPkgHasAttr_Title_XsdtString_ struct {
	Title xsdt.String `xml:"http://www.w3.org/2005/Atom title,attr"`
}

type XsdGoPkgHasAttr_Length_XsdtPositiveInteger_ struct {
	Length xsdt.PositiveInteger `xml:"http://www.w3.org/2005/Atom length,attr"`
}

//	The Atom link construct is defined in section 3.4 of the format spec.
type TlinkType struct {
	XsdGoPkgHasCdata

	XsdGoPkgHasAtts_CommonAttributes

	XsdGoPkgHasAttr_Href_XsdtAnyURI_

	XsdGoPkgHasAttr_Length_XsdtPositiveInteger_

	XsdGoPkgHasAttr_Hreflang_XsdtNmtoken_

	XsdGoPkgHasAttr_Title_XsdtString_

	XsdGoPkgHasAttr_Rel_XsdtString_

}

//	The Atom logo construct is defined in section 4.2.8 of the format spec.
type TlogoType struct {
	XsdGoPkgValue xsdt.AnyURI `xml:",chardata"`

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElems_authorchoicesourceTypeschema_Author_TpersonType_ struct {
	Authors []*TpersonType `xml:"http://www.w3.org/2005/Atom author"`
}

type XsdGoPkgHasElem_authorchoicesourceTypeschema_Author_TpersonType_ struct {
	Author *TpersonType `xml:"http://www.w3.org/2005/Atom author"`
}

type XsdGoPkgHasElem_categorychoicesourceTypeschema_Category_TcategoryType_ struct {
	Category *TcategoryType `xml:"http://www.w3.org/2005/Atom category"`
}

type XsdGoPkgHasElems_categorychoicesourceTypeschema_Category_TcategoryType_ struct {
	Categories []*TcategoryType `xml:"http://www.w3.org/2005/Atom category"`
}

type XsdGoPkgHasElem_contributorchoicesourceTypeschema_Contributor_TpersonType_ struct {
	Contributor *TpersonType `xml:"http://www.w3.org/2005/Atom contributor"`
}

type XsdGoPkgHasElems_contributorchoicesourceTypeschema_Contributor_TpersonType_ struct {
	Contributors []*TpersonType `xml:"http://www.w3.org/2005/Atom contributor"`
}

type XsdGoPkgHasElems_generatorchoicesourceTypeschema_Generator_TgeneratorType_ struct {
	Generators []*TgeneratorType `xml:"http://www.w3.org/2005/Atom generator"`
}

type XsdGoPkgHasElem_generatorchoicesourceTypeschema_Generator_TgeneratorType_ struct {
	Generator *TgeneratorType `xml:"http://www.w3.org/2005/Atom generator"`
}

type XsdGoPkgHasElem_iconchoicesourceTypeschema_Icon_TiconType_ struct {
	Icon *TiconType `xml:"http://www.w3.org/2005/Atom icon"`
}

type XsdGoPkgHasElems_iconchoicesourceTypeschema_Icon_TiconType_ struct {
	Icons []*TiconType `xml:"http://www.w3.org/2005/Atom icon"`
}

type XsdGoPkgHasElem_idchoicesourceTypeschema_Id_TidType_ struct {
	Id *TidType `xml:"http://www.w3.org/2005/Atom id"`
}

type XsdGoPkgHasElems_idchoicesourceTypeschema_Id_TidType_ struct {
	Ids []*TidType `xml:"http://www.w3.org/2005/Atom id"`
}

type XsdGoPkgHasElems_linkchoicesourceTypeschema_Link_TlinkType_ struct {
	Links []*TlinkType `xml:"http://www.w3.org/2005/Atom link"`
}

type XsdGoPkgHasElem_linkchoicesourceTypeschema_Link_TlinkType_ struct {
	Link *TlinkType `xml:"http://www.w3.org/2005/Atom link"`
}

type XsdGoPkgHasElems_logochoicesourceTypeschema_Logo_TlogoType_ struct {
	Logos []*TlogoType `xml:"http://www.w3.org/2005/Atom logo"`
}

type XsdGoPkgHasElem_logochoicesourceTypeschema_Logo_TlogoType_ struct {
	Logo *TlogoType `xml:"http://www.w3.org/2005/Atom logo"`
}

type XsdGoPkgHasElems_rightschoicesourceTypeschema_Rights_TtextType_ struct {
	Rightses []*TtextType `xml:"http://www.w3.org/2005/Atom rights"`
}

type XsdGoPkgHasElem_rightschoicesourceTypeschema_Rights_TtextType_ struct {
	Rights *TtextType `xml:"http://www.w3.org/2005/Atom rights"`
}

type XsdGoPkgHasElem_subtitlechoicesourceTypeschema_Subtitle_TtextType_ struct {
	Subtitle *TtextType `xml:"http://www.w3.org/2005/Atom subtitle"`
}

type XsdGoPkgHasElems_subtitlechoicesourceTypeschema_Subtitle_TtextType_ struct {
	Subtitles []*TtextType `xml:"http://www.w3.org/2005/Atom subtitle"`
}

type XsdGoPkgHasElem_titlechoicesourceTypeschema_Title_TtextType_ struct {
	Title *TtextType `xml:"http://www.w3.org/2005/Atom title"`
}

type XsdGoPkgHasElems_titlechoicesourceTypeschema_Title_TtextType_ struct {
	Titles []*TtextType `xml:"http://www.w3.org/2005/Atom title"`
}

type XsdGoPkgHasElem_updatedchoicesourceTypeschema_Updated_TdateTimeType_ struct {
	Updated *TdateTimeType `xml:"http://www.w3.org/2005/Atom updated"`
}

type XsdGoPkgHasElems_updatedchoicesourceTypeschema_Updated_TdateTimeType_ struct {
	Updateds []*TdateTimeType `xml:"http://www.w3.org/2005/Atom updated"`
}

//	The Atom source construct is defined in section 4.2.11 of the format spec.
type TsourceType struct {
	XsdGoPkgHasElems_authorchoicesourceTypeschema_Author_TpersonType_

	XsdGoPkgHasElems_categorychoicesourceTypeschema_Category_TcategoryType_

	XsdGoPkgHasElems_contributorchoicesourceTypeschema_Contributor_TpersonType_

	XsdGoPkgHasElems_generatorchoicesourceTypeschema_Generator_TgeneratorType_

	XsdGoPkgHasElems_iconchoicesourceTypeschema_Icon_TiconType_

	XsdGoPkgHasElems_idchoicesourceTypeschema_Id_TidType_

	XsdGoPkgHasElems_linkchoicesourceTypeschema_Link_TlinkType_

	XsdGoPkgHasElems_logochoicesourceTypeschema_Logo_TlogoType_

	XsdGoPkgHasElems_rightschoicesourceTypeschema_Rights_TtextType_

	XsdGoPkgHasElems_subtitlechoicesourceTypeschema_Subtitle_TtextType_

	XsdGoPkgHasElems_titlechoicesourceTypeschema_Title_TtextType_

	XsdGoPkgHasElems_updatedchoicesourceTypeschema_Updated_TdateTimeType_

	XsdGoPkgHasAtts_CommonAttributes

}

type TuriType struct {
	XsdGoPkgValue xsdt.AnyURI `xml:",chardata"`

	XsdGoPkgHasAtts_CommonAttributes

}

type TdateTimeType struct {
	XsdGoPkgValue xsdt.DateTime `xml:",chardata"`

	XsdGoPkgHasAtts_CommonAttributes

}

type XsdGoPkgHasElem_Feed struct {
	Feed *TfeedType `xml:"http://www.w3.org/2005/Atom feed"`
}

type XsdGoPkgHasElems_Feed struct {
	Feeds []*TfeedType `xml:"http://www.w3.org/2005/Atom feed"`
}

type XsdGoPkgHasElem_Entry struct {
	Entry *TentryType `xml:"http://www.w3.org/2005/Atom entry"`
}

type XsdGoPkgHasElems_Entry struct {
	Entries []*TentryType `xml:"http://www.w3.org/2005/Atom entry"`
}
